call mccap blood sand
call mccap white sand
call mccap orange sand
call mccap magenta sand
call mccap light_blue sand
call mccap yellow sand
call mccap lime sand
call mccap pink sand
call mccap gray sand
call mccap light_gray sand
call mccap cyan sand
call mccap purple sand
call mccap blue sand
call mccap green sand
call mccap brown sand
call mccap black sand